language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
#  - "nightly"
# command to install dependencies
install:
  - "pip install setuptools wheel coveralls coverage"
  - "pip install --trusted-host www.edna-site.org -r requirements_travis.txt"
  - "python info_platform.py"
  - "python setup.py build"
  - "pip install ."
# command to run tests
script:
  - "python setup.py build test"
#  - "python ./run_tests.py"
  - "coverage run ./run_tests.py"

after_success:
    coveralls